# ARCHITECTURE 
#    Internet
#	│
#       ▼
# Internet Gateway
#	│
#       ▼
#	VPC
#	│
#	├── Internet Gateway
#	│        │
#	│       ▼
#	│  Attached to VPC
#	│
#	├── Public Subnet
#	│
# 	│── Public Route Table
#	│           │
#	│           ▼
#	│        0.0.0.0/0
#	│           │
#	│           ▼
#	│     Internet Gateway
#	│
#	└── Security Group
#		│
#       	▼
#	       EC2
#		│
#	        ├── Security Group
#	        └── Public IP

AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Week 3 Task 3 - CloudFormation template that provisions
  a VPC, public subnet, security group and EC2 instance.

Parameters:

# Public IPv4 Address
  MyIP: 
    Type: String
    Description: Enter your public IPv4 address in CIDR notation
    Default: 0.0.0.0/0

Resources:

# VPC
  Week3VPC:
    Type: AWS::EC2::VPC
    
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: week3-cloudformation-vpc

# Internet Gateway
  Week3InternetGateway:
    Type: AWS::EC2::InternetGateway
    
    Properties:
      Tags:
        - Key: Name
          Value: week3-igw

  AttachGateway: 
    Type: AWS::EC2::VPCGatewayAttachment
    
    Properties:
      VpcId: !Ref Week3VPC
      InternetGatewayId: !Ref Week3InternetGateway

# Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    
    Properties:
      VpcId: !Ref Week3VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-south-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: week3-public-subnet

# Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    
    Properties:
      VpcId: !Ref Week3VPC
      Tags:
        - Key: Name
          Value: week3-public-rt

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Week3InternetGateway

# Route Table Association
  PublicSubnetRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation

    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

# Web Security Group
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup

    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref Week3VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: week3-web-sg

# EC2 Instance
# Launches an Amazon Linux EC2 instance inside the public subnet and associates it with the web security group.
# Uses the latest Amazon Linux 2023 AMI from AWS Systems Manager Parameter Store.
  WebServerInstance:
    Type: AWS::EC2::Instance

    Properties:
      InstanceType: t3.micro

      #Latest Amazon Linux 2023 AMI
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'

      KeyName: week1-task3-ec2-key

      SubnetId: !Ref PublicSubnet

      SecurityGroupIds:
        - !Ref WebSecurityGroup

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          #same as the deploy.sh file created in Week 2
          dnf update -y
          dnf install -y httpd
          systemctl enable httpd
          systemctl start httpd

          #echo "<h1>Hello from CloudFormation!</h1>" > /var/www/html/index.html
          #Created homepage
          cat <<EOF > /var/www/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <title>Week 3 - CloudFormation</title>
          </head>
          <body>
            <h1>🚀 AWS CloudFormation Deployment Successful!</h1>
              <p>Infrastructure successfully provisioned using AWS CloudFormation.</p>
              <ul>
                <li>VPC</li>
                <li>Public Subnet</li>
                <li>Internet Gateway</li>
                <li>Route Table</li>
                <li>Security Group</li>
                <li>EC2 Instance</li>
              </ul>

              <p>Created using AWS CloudFormation (Infrastructure as Code)</p>
              <p> AWS Internship • Week 3</p>

          </body>
          </html>
          EOF

      Tags:
        - Key: Name
          Value: week3-web-server

Outputs:

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref WebServerInstance

  PublicIP:
    Description: Public IP Address
    Value: !GetAtt WebServerInstance.PublicIp      #this asks CF what's the current Public IP of this EC2 instance

  PublicDNS:
    Description: Public DNS Name
    Value: !GetAtt WebServerInstance.PublicDnsName
